apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-branch1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-branch1
  template:
    metadata:
      labels:
        app: myapp-branch1
    spec:
      containers:
      - name: myapp
        image: myapp:branch1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
